---
    certDays: 45
    certExt: "subjectAltName=DNS:{{item.value.commonName }}"
    certSubject: '/C=US/ST=Massachusetts/L=Boston/O=The Jetsons/OU=Engineering/CN={{ item.value.commonName }}'
    crtName: "{{path}}/{{ item.value.commonName|trim }}-{{ timestamp }}.crt"
    keyName: "{{path}}/{{ item.value.commonName|trim }}-{{ timestamp }}.key" 
