---
 
  
    - name: Create self signed certificate 
      command: 'openssl req -x509 -newkey rsa:2048  -sha256 -nodes -keyout {{ keyName }} -out {{ crtName }} -subj "{{ certSubject }}" -days {{ certDays }} -addext {{ certExt }} ' 
      delegate_to: localhost
      loop:  "{{ certNames2Renew | dict2items}}"


